apiVersion: v1
kind: Secret
metadata:
  name: jira-secret
  namespace: incident-system
type: Opaque
stringData:
  JIRA_BASE_URL: "https://ldlq2005.atlassian.net"
  JIRA_EMAIL: "ldlq2005@gmail.com"
  JIRA_TOKEN: "JIRA_API_TOKEN"
  JIRA_PROJECT_KEY: "QN"
