name: Full Production Deploy (Terraform + EKS + Frontend) 

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
          - bootstrap

env:
  IMAGE_TAG: ${{ github.sha }}
  PROJECT_NAME: cloud-incident-system
  AWS_REGION: ${{ vars.AWS_REGION }}
  DYNAMODB_TABLE_NAME: cloud-incident-table
  UPLOAD_BUCKET_PREFIX: cloud-incident-upload
  FRONTEND_BUCKET_PREFIX: cloud-incident-frontend

jobs:
  bootstrap-backend:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'bootstrap'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Bootstrap (ONLY ONCE)
        working-directory: infra/bootstrap
        run: |
          terraform init
          terraform apply -auto-approve


  deploy_all:
    runs-on: ubuntu-latest
    if: github.event.inputs.action != 'bootstrap'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # =========================
      # AWS LOGIN
      # =========================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      # =========================
      # SETUP TERRAFORM
      # =========================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init -reconfigure

      # =========================
      # DESTROY (OPTION)
      # =========================
      - name: Update kubeconfig
        if: github.event.inputs.action == 'destroy'
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Delete Igress 
        if: github.event.inputs.action == 'destroy'
        working-directory: k8s
        run: |
          kubectl delete -f k8s/ingress.yaml

      - name: Terraform Init (Bootstrap)
        if: github.event.inputs.action == 'destroy'
        working-directory: infra
        run: terraform init -reconfigure

      - name: Terraform Init (Bootstrap)
        if: github.event.inputs.action == 'destroy'
        working-directory: infra/bootstrap
        run: terraform init -reconfigure

      - name: Get TFSTATE bucket name (exclude from cleanup)
        if: github.event.inputs.action == 'destroy'
        working-directory: infra/bootstrap
        run: |
          echo "TFSTATE_BUCKET_NAME=cloud-incident-system-tf-state" >> $GITHUB_ENV

      - name: Delete versioned S3 buckets (exclude tfstate bucket)
        if: github.event.inputs.action == 'destroy'
        working-directory: infra
        shell: pwsh
        run: |
          echo "TFSTATE_BUCKET_NAME = ${TFSTATE_BUCKET_NAME}"
          ./deletebucket.ps1
          
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: infra
        run: terraform destroy -auto-approve
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
          TF_VAR_dynamodb_table_name: ${{ env.DYNAMODB_TABLE_NAME }}
          TF_VAR_upload_bucket_prefix: ${{ env.UPLOAD_BUCKET_PREFIX }}
          TF_VAR_frontend_bucket_prefix: ${{ env.FRONTEND_BUCKET_PREFIX }}

          TF_VAR_jira_base_url: ${{ vars.JIRA_BASE_URL}}
          TF_VAR_jira_email: ${{ secrets.JIRA_EMAIL }}
          TF_VAR_jira_token: ${{ secrets.JIRA_API_TOKEN }}
          TF_VAR_jira_project_key: ${{ vars.PROJECT_KEY }}

      - name: Terraform Destroy Bootstrap (Backend State)
        if: github.event.inputs.action == 'destroy'
        working-directory: infra/bootstrap
        run: terraform destroy -auto-approve

      # =========================
      # PHASE 1: APPLY INFRA CORE
      # =========================
      - name: Terraform Apply Infra Core (EKS + Dynamo + Cognito + SSM)
        if: github.event.inputs.action != 'destroy'
        working-directory: infra
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_aws_region: ${{ env.AWS_REGION }}

          TF_VAR_dynamodb_table_name: ${{ env.DYNAMODB_TABLE_NAME }}
          TF_VAR_upload_bucket_prefix: ${{ env.UPLOAD_BUCKET_PREFIX }}
          TF_VAR_frontend_bucket_prefix: ${{ env.FRONTEND_BUCKET_PREFIX }}

          # Backend ALB DNS chưa có, để empty hoặc dummy
          TF_VAR_backend_alb_dns: "example.com"

          
          TF_VAR_jira_base_url: ${{ vars.jira_base_url}} 
          TF_VAR_jira_email: ${{ secrets.JIRA_EMAIL }}
          TF_VAR_jira_token: ${{ secrets.JIRA_API_TOKEN }}
          TF_VAR_jira_project_key: ${{ vars.project_key }}

      - name: Export Terraform Outputs
        if: github.event.inputs.action != 'destroy'
        working-directory: infra
        run: terraform output -json > tf_outputs.json

      - name: Parse Terraform Outputs
        if: github.event.inputs.action != 'destroy'
        working-directory: infra
        run: |
          echo "UPLOAD_BUCKET_NAME=$(jq -r '.upload_bucket_name.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "COGNITO_USER_POOL_ID=$(jq -r '.cognito_user_pool_id.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "COGNITO_CLIENT_ID=$(jq -r '.cognito_client_id.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "FRONTEND_BUCKET=$(jq -r '.frontend_bucket.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "VPC_ID=$(jq -r '.vpc_id.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=$(jq -r '.cloudfront_distribution_id.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "FRONTEND_URL=$(jq -r '.frontend_url.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "DDB_TABLE_NAME=$(jq -r '.dynamodb_table_name.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "JIRA_BASE_URL=$(jq -r '.jira_ssm_params.value.base_url' tf_outputs.json)" >> $GITHUB_ENV
          echo "JIRA_EMAIL=$(jq -r '.jira_ssm_params.value.email' tf_outputs.json)" >> $GITHUB_ENV
          echo "JIRA_TOKEN=$(jq -r '.jira_ssm_params.value.token' tf_outputs.json)" >> $GITHUB_ENV
          echo "JIRA_PROJECT_KEY=$(jq -r '.jira_ssm_params.value.project_key' tf_outputs.json)" >> $GITHUB_ENV
  

      # =========================
      # BUILD BACKEND IMAGE
      # =========================
      - name: Create ECR repository if not exists
        if: github.event.inputs.action != 'destroy'
        run: |
          aws ecr describe-repositories --repository-names incident-api \
          || aws ecr create-repository --repository-name incident-api --region ${{ env.AWS_REGION }}

      - name: Set ECR repo URI
        if: github.event.inputs.action != 'destroy'
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REPO_URI="$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/incident-api"
          echo "repo_url=$REPO_URI" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        if: github.event.inputs.action != 'destroy'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend Docker image
        if: github.event.inputs.action != 'destroy'
        run: docker build -t incident-api:${IMAGE_TAG:0:7} ./backend

      - name: Tag + Push backend image
        if: github.event.inputs.action != 'destroy'
        run: |
          docker tag incident-api:${IMAGE_TAG:0:7} $repo_url:${IMAGE_TAG:0:7}
          docker push $repo_url:${IMAGE_TAG:0:7}

      # =========================
      # UPDATE KUBECONFIG
      # =========================
      - name: Update kubeconfig
        if: github.event.inputs.action != 'destroy'
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Setup kubectl
        if: github.event.inputs.action != 'destroy'
        uses: azure/setup-kubectl@v4

      # =========================
      # APPLY K8S MANIFESTS
      # =========================
      - name: Apply Namespace + SA + Service
        if: github.event.inputs.action != 'destroy'
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/backend-SA.yaml
          kubectl apply -f k8s/alb-sa.yaml

          kubectl delete secret jira-secret -n incident-system --ignore-not-found

          kubectl create secret generic jira-secret \
            -n incident-system \
            --from-literal=JIRA_BASE_URL=https://ldlq2005.atlassian.net \
            --from-literal=JIRA_EMAIL=${{ secrets.JIRA_EMAIL }} \
            --from-literal=JIRA_TOKEN=${{ secrets.JIRA_API_TOKEN }} \
            --from-literal=JIRA_PROJECT_KEY=QN

          kubectl apply -f k8s/service.yaml

      # =========================
      # INSTALL AWS LOAD BALANCER CONTROLLER
      # =========================
      - name: Setup Helm
        if: github.event.inputs.action != 'destroy'
        uses: azure/setup-helm@v4

      - name: Install AWS Load Balancer Controller
        if: github.event.inputs.action != 'destroy'
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update

          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
            --namespace kube-system \
            --set clusterName="${{ secrets.EKS_CLUSTER_NAME }}" \
            --set region="${{ env.AWS_REGION }}" \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller \
            --set vpcId="$VPC_ID" \
            --wait

      # =========================
      # APPLY INGRESS
      # =========================
      - name: Apply Ingress
        if: github.event.inputs.action != 'destroy'
        run: kubectl apply -f k8s/ingress.yaml

      - name: Wait for ALB Ingress to be Ready
        if: github.event.inputs.action != 'destroy'
        run: |
          set -e
          INGRESS_NAME="incident-backend-ingress"
          NAMESPACE="incident-system"

          echo "Waiting for ingress $INGRESS_NAME in namespace $NAMESPACE ..."

          for i in $(seq 1 40); do
            HOSTNAME=$(kubectl get ingress $INGRESS_NAME -n $NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)

            if [ -n "$HOSTNAME" ]; then
              echo "ALB ready: $HOSTNAME"
              echo "ALB_DNS_NAME=$HOSTNAME" >> $GITHUB_ENV
              exit 0
            fi

            echo "[$i/40] ALB not ready yet..."
            sleep 15
          done

          echo "ALB not ready after timeout"
          exit 1

      # =========================
      # APPLY DEPLOYMENT
      # =========================
      - name: Render Deployment from Template
        if: github.event.inputs.action != 'destroy'
        run: |
          export AWS_REGION="${{ env.AWS_REGION }}"
          export IMAGE_TAG="${IMAGE_TAG:0:7}"
          export ECR_REPO_URI="$repo_url"

          envsubst < k8s/deployment.yaml.tpl > k8s/deployment.yaml
          cat k8s/deployment.yaml

      - name: Apply Deployment
        if: github.event.inputs.action != 'destroy'
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment incident-api -n incident-system --timeout=300s

      # =========================
      # PHASE 2: UPDATE CLOUDFRONT ORIGIN WITH ALB DNS
      # =========================
      - name: Terraform Apply Update CloudFront Origin
        if: github.event.inputs.action != 'destroy'
        working-directory: infra
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_aws_region: ${{ env.AWS_REGION }}

          TF_VAR_dynamodb_table_name: ${{ env.DYNAMODB_TABLE_NAME }}
          TF_VAR_upload_bucket_prefix: ${{ env.UPLOAD_BUCKET_PREFIX }}
          TF_VAR_frontend_bucket_prefix: ${{ env.FRONTEND_BUCKET_PREFIX }}

          # QUAN TRỌNG: chỉ hostname, không có http://
          TF_VAR_backend_alb_dns: ${{ env.ALB_DNS_NAME }}

          
          TF_VAR_jira_base_url: ${{ vars.jira_base_url}} 
          TF_VAR_jira_email: ${{ secrets.JIRA_EMAIL }}
          TF_VAR_jira_token: ${{ secrets.JIRA_API_TOKEN }}
          TF_VAR_jira_project_key: ${{ vars.project_key }}

      # =========================
      # EXPORT OUTPUT AGAIN (AFTER UPDATE CLOUDFRONT)
      # =========================
      - name: Export Terraform Outputs (After CloudFront Update)
        if: github.event.inputs.action != 'destroy'
        working-directory: infra
        run: terraform output -json > tf_outputs.json

      - name: Parse Terraform Outputs (After CloudFront Update)
        if: github.event.inputs.action != 'destroy'
        working-directory: infra
        run: |
          echo "FRONTEND_URL=$(jq -r '.frontend_url.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "CLOUDFRONT_DISTRIBUTION_ID=$(jq -r '.cloudfront_distribution_id.value' tf_outputs.json)" >> $GITHUB_ENV

      # =========================
      # BUILD + DEPLOY FRONTEND
      # =========================
      - name: Generate frontend .env
        if: github.event.inputs.action != 'destroy'
        working-directory: frontend
        run: |
          rm -f .env
          cat > .env <<EOF
          VITE_API_URL=/api
          VITE_COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
          VITE_COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
          VITE_AWS_REGION=${{ env.AWS_REGION }}
          VITE_UPLOAD_BUCKET_NAME=$UPLOAD_BUCKET_NAME
          EOF

      - name: Setup Node
        if: github.event.inputs.action != 'destroy'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        if: github.event.inputs.action != 'destroy'
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        if: github.event.inputs.action != 'destroy'
        working-directory: frontend
        run: npm run build

      - name: Deploy frontend to S3
        if: github.event.inputs.action != 'destroy'
        working-directory: frontend
        run: |
          aws s3 sync dist s3://${FRONTEND_BUCKET} --delete

          aws s3 sync dist s3://${FRONTEND_BUCKET} \
            --exclude "index.html" \
            --cache-control "max-age=31536000,public,immutable"

          aws s3 cp dist/index.html s3://${FRONTEND_BUCKET}/index.html \
            --cache-control "no-cache"

      - name: Invalidate CloudFront
        if: github.event.inputs.action != 'destroy'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
            --paths "/*"

      # =========================
      # PRINT URLS
      # =========================
      - name: Print Backend and Frontend URL
        if: github.event.inputs.action != 'destroy'
        run: |
          echo "Backend ALB DNS:"
          echo "${ALB_DNS_NAME}"

          echo "Frontend URL:"
          echo "${FRONTEND_URL}"